import Head from "next/head";
import Hero from "../components/Hero";
import { createClient } from "contentful";
import MenuGrid from "../components/MenuGrid/MenuGrid";
import Heading from "../components/Heading";
import NaseHodnotyPage from "../components/NaseHodnoty/HodnotyPage";
import HodnotyPage from "../components/NaseHodnoty/HodnotyPage";
import { useEffect, useState } from "react";
import RecenziePage from "../components/Recenzie/RecenziePage";
import ContactPage from "../components/Kdenasnajdete/ContactPage";

export default function Home(props: any) {
  const [isMobile, setIsMobile] = useState(false);
  const [windowWidth, setWindowWidth] = useState(0);

  const handleResize = () => {
    setWindowWidth(window.innerWidth);
    if (window.innerWidth < 600) {
      setIsMobile(true);
    } else {
      setIsMobile(false);
    }
  };

  useEffect(() => {
    handleResize();
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  return (
    <>
      <Head>
        <title>Paluba Rozvoz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-whiteBg">
        <Hero />
        <MenuGrid
          isMobile={isMobile}
          windowWidth={windowWidth}
          categories={props.categories}
        />
        <HodnotyPage isMobile={isMobile} />
        <RecenziePage />
        <ContactPage />
      </main>
    </>
  );
}

export async function getServerSideProps(props: any) {
  const client = createClient({
    space: "xx2dzasjcpic",
    accessToken: "Shkp5PbccjOlxcv1F0xI-ZfxwZ0i2lN9lv_6hC8eS4s",
  });

  const categories = await client.getEntries({
    content_type: "category",
    include: 10,
  });

  return {
    props: {
      categories: categories.items,
    }, // will be passed to the page component as props
  };
}
